{{- if .Values.nrf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: {{ .Values.global.namespace }}
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.2
      description: NRF initial local configuration

    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://mongodb:27017

      sbi:
        scheme: http
        registerIPv4: nrf
        bindingIPv4: 0.0.0.0
        port: 8000

        cert:
          pem: cert/nrf.pem
          key: cert/nrf.key

        rootcert:
          pem: cert/root.pem
          key: cert/root.key

        oauth: true

      DefaultPlmnId:
        mcc: 208
        mnc: 93

      serviceNameList:
        - nnrf-nfm
        - nnrf-disc

      metrics:
        enable: false
        scheme: http
        bindingIPv4: 0.0.0.0
        port: 9091
        tls:
          pem: cert/nrf.pem
          key: cert/nrf.key
        namespace: free5gc

    logger:
      enable: true
      level: info
      reportCaller: false
{{- end }}
