apiVersion: v1
kind: Service
metadata:
  name: pcf
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: free5gc-pcf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
      protocol: TCP
