apiVersion: v1
kind: ConfigMap
metadata:
  name: n3iwf-config
  namespace: {{ .Values.global.namespace }}
data:
  n3iwfcfg.yaml: |
    info:
      version: 1.0.5
      description: N3IWF initial local configuration

    configuration:
      n3iwfInformation:
        globalN3IWFID:
          plmnID:
            mcc: "208"
            mnc: "93"
          n3iwfID: 135
        name: free5GC_N3IWF
        supportedTAList:
          - tac: "000001"
            broadcastPlmnList:
              - plmnID:
                  mcc: "208"
                  mnc: "93"
                taiSliceSupportList:
                  - snssai:
                      sst: 1
                      sd: "010203"

      amfSCTPAddresses:
        - ip:
            - "10.108.147.110"
          port: 38412

      nasTcpPort: 20000
      ikeBindAddress: "192.168.122.231"
      ipSecTunnelAddress: "10.200.200.1"
      n3iwfGtpBindAddress: "192.168.122.231"
      ueIpAddressRange: "10.200.200.0/24"
      fqdn: "n3iwf.free5gc.org"
      xfrmInterfaceName: "xfrmi"
      xfrmInterfaceID: 1
      privateKey: "/free5gc/cert/n3iwf.key"
      certificateAuthority: "/free5gc/cert/n3iwf.pem"
      certificate: "/free5gc/cert/n3iwf.pem"
      livenessCheck:
        enable: true
        transFreq: 60s
        maxRetryTimes: 4

    logger:
      enable: true
      level: info
      reportCaller: false
