apiVersion: v1
kind: Service
metadata:
  name: n3iwf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: free5gc-n3iwf
spec:
  type: LoadBalancer
  selector:
    app: free5gc-n3iwf
  ports:
    - name: ike
      port: 500
      targetPort: 500
      protocol: UDP
    - name: ike-natt
      port: 4500
      targetPort: 4500
      protocol: UDP
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
