apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-config
  namespace: {{ .Values.global.namespace }}
data:
  webuicfg.yaml: |
    info:
      version: 1.0.3
      description: WEBUI initial local configuration

    configuration:
      mongodb:
        name: free5gc
        url: mongodb://mongodb:27017
      nrfUri: http://nrf:8000
      nrfCertPem: cert/nrf.pem
      webServer:
        scheme: http
        ipv4Address: 0.0.0.0
        port: 5000
      billingServer:
        enable: true         # ← was false, must be true for validator
        hostIPv4: 0.0.0.0
        listenPort: 2122
        portRange:
          start: 2123
          end: 2130
        basePath: /tmp/webconsole
        port: 2121
        tls:
          pem: cert/chf.pem
          key: cert/chf.key

    logger:
      enable: true
      level: info
      reportCaller: false
