{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: free5gc-mongodb
spec:
  type: ClusterIP
  selector:
    app: free5gc-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app: free5gc-mongodb
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: free5gc-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-mongodb
  template:
    metadata:
      labels:
        app: free5gc-mongodb
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - mongod
            - "--port"
            - "27017"
            - "--bind_ip_all"
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
{{- end }}
