apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: {{ .Release.Namespace }}
  labels:
    app: free5gc-upf
spec:
  replicas: 1
  
  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: free5gc-upf

  template:
    metadata:
      labels:
        app: free5gc-upf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"upf-n3","ips":["192.168.122.232/24"]}]'

    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker1

      containers:
        - name: upf
          image: "{{ .Values.image.registry }}/upf:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - ./upf
            - -c
            - ./config/upfcfg.yaml

          securityContext:
            privileged: true

          ports:
            - name: pfcp
              containerPort: 8805
              protocol: UDP

            - name: gtpu
              containerPort: 2152
              protocol: UDP

          volumeMounts:
            - name: upf-config
              mountPath: /free5gc/config/upfcfg.yaml
              subPath: upfcfg.yaml
              readOnly: true

            - name: dev-net-tun
              mountPath: /dev/net/tun


      volumes:
        - name: upf-config
          configMap:
            name: upf-config

        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
