{{- if .Values.upf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: {{ .Release.Namespace }}
  labels:
    app: free5gc-upf
spec:
  type: ClusterIP
  selector:
    app: free5gc-upf
  ports:
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
{{- end }}
